### ISSUE TITLE
[SEP] token not added between transactions in TabGPT

### ISSUE THREAD

**Issue by brandonlockhart** [IBM/TabFormer#10]
Hello,

From my understanding of the paper, for the TabGPT model, sequences of ten transactions are passed with the [SEP] token between the transactions.

However, after looking at the [code](https://github.com/IBM/TabFormer/blob/5a9e52ba493150632c15faf7b3cc80b710ca927a/dataset/card.py#L191), it seems like a [SEP] token is not added between the transactions; `self.mlm` is `False` here since the `--mlm` flag is not included in the command provided in the README.

Thank you very much for any clarification on this.

**Comment by ink-pad** [comment]
Hello @brandonlockhart: 

Thank you for your message. In practice, we didn't find significant between both. As eventually you need to create blocks of hidden states accordingly. However, I must admit we had made this observation very early in our experiments, so feel free to try both and see what works better for your use-case.

**Comment by brandonlockhart** [comment]
Interesting. Thank you for your explanation @ink-pad
