### ISSUE TITLE
Cannot open transactions.tgz file

### ISSUE THREAD

**Issue by RiskModellingResearch** [IBM/TabFormer#12]
Hello,

Please can you help me with the unzipping transactions data. My program says that the archive is damaged.

Thanks!

**Comment by ink-pad** [comment]
Hello @RiskModellingResearch ,

This seems strange! Did you download the data from : https://ibm.box.com/v/tabformer-data ?

**Comment by RiskModellingResearch** [comment]
Oh, yes, I found it! Thank you and sorry for not quick response.
