### ISSUE TITLE
Keep Getting Warning of "Please add an explicit pip dependency. I'm adding one for you, but still nagging you"

### ISSUE THREAD

**Issue by tim5go** [IBM/TabFormer#15]
As titled, getting lots of warning messages when creating the virtual environment.

I guess it's related to this thread:
https://stackoverflow.com/questions/67081266/conda-yml-file-prompts-please-add-an-explicit-pip-dependency

To solve it / suppress the warning, maybe it is better to add an explicit dependency of `pip` in the yaml file.

**Comment by yair-schiff** [comment]
Thanks for pointing this out. Warning should be gone with this commit https://github.com/IBM/TabFormer/commit/ebb7cd68ee1897599568107740bc452104bbbaf8
