### ISSUE TITLE
Number of fields

### ISSUE THREAD

**Issue by albusdemens** [IBM/TabFormer#19]
A (very minor) correction for the README file: the number of fields is 15, not 12 (see [here](https://github.com/IBM/TabFormer/blob/main/README.md#credit-card-transaction-dataset)).

**Comment by nandhakumarsuriya** [comment]
@albusdemens Number of fields is actually 12 , since 'year',  'month',  'day',  'time' fields are preprocessed into single field 'Timestamp'.  So its not equal to 15
