### ISSUE TITLE
Is TABGPT really privacy-preserving?

### ISSUE THREAD

**Issue by patrickmesana** [IBM/TabFormer#20]
Hello,
It seems to me that you don't give any guarantee in you paper that someone would not be able to attack  the generated dataset (e.g. membership attacks)?

**Comment by ymroueh** [comment]
Hi Patrick , Thanks for your questions . 

Regarding tabbert we experimented with hashing tabbert embeddings using random projection followed by taking the sign of the projection, the performance of these embeddings in fraud detection were on par with the unhashed embedding. This hashing would guarantee the privacy of TabBERT, many previous works showed that such mechanism ensure differential privacy. 

For TabGPT the paper does not offer formal guarantees indeed, the only claim we make is that as long as we sample from TabGPT novel samples that are close in distribution but individually different from training , privacy will be preserved. This can be done as a post processing. 

Another mechanism is to generate from tabGPT and then embed with TabBERT and using the hashing mechanism and release this embedded data , this can guarantee privacy but the data will not be interpretable. 

We left  for a future work to incorporate differential privacy  mechanisms with TabGPT training to have formal guarantees. We will update our repos when we have differential privacy incorporated.

**Comment by patrickmesana** [comment]
Thank you for your response. Very nice of you to take the time.

Do you you have any paper to recommend me that shows that the hashing guarantees the privacy of TabBERT?  I read a couple of articles about the subject, one in particular ["Privacy via the J-L Transform"](https://arxiv.org/pdf/1204.2606.pdf) that suggests you need to add noise to the random projections to frame it as (e, δ)-differential private.

Intuitivement, I can see privacy issues that the hashing would not resolve. For exemple, I imagine an ML task where your embeddings (hashed or not) could be used to give the probability of identifying one person given 1 of his transaction. Thus, even if feature reconstruction may be harder because of the hashing, re-identifying or membership attacks may not be harder.

**Comment by ymroueh** [comment]
yes I was thinking of reconstruction attacks.  For certain tasks JL is enough by itself see this [paper](https://arxiv.org/pdf/1204.2136.pdf).  After hashing we need to perturb ( flip randomly some of the bits if it is binary hashing, or perturb with noise if it is real valued hashing as you said ) the outcome to protect against membership attacks. I was thinking of the paper you shared , you can check references in  section  5.2 in                                 [this paper](http://proceedings.mlr.press/v124/gondara20a/gondara20a.pdf) it surveys nicely recent previous works on  data release with random projections.  (This paper itself deals with private release of small datasets. )

**Comment by patrickmesana** [comment]
Thank you for sharing :)
