### ISSUE TITLE
predicting using the trained model

### ISSUE THREAD

**Issue by seekingdeep** [IBM/TabFormer#4]
@ink-pad
Hi there,
now that i trained a PRSA bert model, how to inference on a .csv file for perhaps classification.
Can you contact me by email, you will find it in my profile, i want to ask some question.

**Comment by ink-pad** [comment]
Hi @seekingdeep, 

Glad to hear that you managed to train the bert model. 

You could train your favorite classifier on top of this trained BERT features (MLP or LSTM) , and then you can do inference using BERT and the classifier. Note that we did not include the classification pipeline in the public code. Please refer to the [paper](https://arxiv.org/abs/2011.01843) for details.

**Comment by seekingdeep** [comment]
@ink-pad can you contact me the email is at my profile
