### ISSUE TITLE
LFS Clone of credit card data not working

### ISSUE THREAD

**Issue by RuanJohn** [IBM/TabFormer#6]
Good day, 

When trying to lfs pull the credit card data I get the following error: 

batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Could you please help? 

Kind regards
Ruan

**Comment by ink-pad** [comment]
@RuanJohn : Thank you for your interest, @RuanJohn. 

>batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. 

Ah - that seems weird. I know people who have downloaded it and it worked for them. I am going raise a ticket with Github Helpdesk to zero in on the issue. The GitHub Helpdesk are very responsive - I will update once I hear from them.

**Comment by RuanJohn** [comment]
@ink-pad Thank you for your reply. 

Please let me know once the Github help desk has given any feedback. 

Thank you for your help and your amazing work! I am inspired!

**Comment by ink-pad** [comment]
@RuanJohn : The LFS thing needs to some time to get it to work for now. I need to raise some requests internally for the bandwidth. 

However, I have now a [directly link](https://ibm.box.com/v/tabformer-data) to the data as well, which you can access to download the data. Once you confirm that it works, I will go ahead and update the readme accordingly as well.

**Comment by RuanJohn** [comment]
@ink-pad Thank you for your reply and your help. The direct link worked perfectly!
