### ISSUE TITLE
How to reduce model size for fitting gpu memory

### ISSUE THREAD

**Issue by Firyuza** [IBM/TabFormer#7]
Hi!

I have gpu with 32 Gb, but it's not enough for training model using your source code and predefined config. 
Please, can you explain how to reduce model params.
I've already reduced embedding dim and nrof attention heads, but maybe you know better way?

Thanks!

**Comment by ink-pad** [comment]
Hello @Firyuza,

32GB should be sufficient to run experiments (w/ instructions provided; and default config). Could you provide more information as to what model are you trying to run and on what dataset?

**Comment by Firyuza** [comment]
Thanks for quick feedback!

I use the predefined config that I've taken from this repo.

I use my custom dataset, where the length of my transaction history is 800. So from getitem method I return the sequence of 800 length.

Thanks!

**Comment by ink-pad** [comment]
Ah - the maximum sequence length in our experiments were 120 (12 fields*10 rows). How many fields are there for each row, in your custom dataset? What is your vocabulary size? 

Few other things one could try is reducing the number of rows per sample as well. The relevant argument for that is `seq_len`. Additionally, try reducing the batch size too.

**Comment by ink-pad** [comment]
@Firyuza : 

Closing this issue. Please free to re-open if you have more questions.
