### ISSUE TITLE
Error in TabFormerGPT2LMHeadModel class

### ISSUE THREAD

**Issue by 52cash** [IBM/TabFormer#8]
Hi,

Noticed that input_only is an invalid argument to get_field_keys method in vocab: _**(line 49)**_
`field_names = self.vocab.get_field_keys(input_only=True, ignore_special=True)`

Should it be this instead?
`field_names = self.vocab.get_field_keys(remove_target=True, ignore_special=True)`

Also, are you able to include code snippet for generation of synthetic data using trained GPT-2?
Would like to recreate the results stated in your paper. Thank you

**Comment by J-JY** [comment]
Also, are you going to include code snippet for the Fraud Detection Tasks and the Regression Tasks in your paper? Thank you very much

**Comment by J-JY** [comment]
Also, are you going to include code snippet for the Fraud Detection Tasks and the Regression Tasks in your paper? Thank you very much

**Comment by ink-pad** [comment]
@52cash : 
Thanks for reporting it. What you have mentioned is indeed correct - I have fixed this in the latest commit; `5a9e52b`.

**Comment by J-JY** [comment]
来信收悉，顺祝恭安！This is an automatic reply, confirming that your e-mail was received.Thank you！
