### ISSUE TITLE
How to load the pretrained model in Fraud Detection Tasks

### ISSUE THREAD

**Issue by J-JY** [IBM/TabFormer#9]
Hi,
It's very nice of you to opensource the code.
I've run your code and got the model in checkpoints.
When I tried to reproduce the results in Fraud Detection Tasks, I tried many kinds of methods but failed to load the pretrained model.
For example, 
model=TabFormerHierarchicalLM.from_pretrained("model_path")
but it failed.
Could you tell me how to load the the pretrained model? Thanks a lot.

**Comment by ink-pad** [comment]
Hello @J-JY ,

Thank you for the message.

Could you provide more information what error you get? I am yet to update this public repository with the downstream tasks code and hoping to make it available around the conference (ICASSP) week.
